# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples
export x=273
# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Avoid duplicates
HISTCONTROL=ignoredups:erasedups
# When the shell exits, append to the history file instead of overwriting it
shopt -s histappend

# After each command, append to the history file and reread it
PROMPT_COMMAND="${PROMPT_COMMAND:+$PROMPT_COMMAND$'\n'}history -a; history -c; history -r"

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=-1
HISTFILESIZE=20000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

if [ -x /usr/bin/dircolors ]; then
    test -r "$HOME/.dircolors" \
        && eval "$(dircolors -b "$HOME/.dircolors")" \
        || eval "$(dircolors -b)"

    alias ls='ls --color=auto'
    alias grep='grep --color=auto'
fi

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# colored GCC warnings and errors
#export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bashrc_aliases ]; then
    . ~/.bashrc_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

alias pycharm=~/bin/pycharm-2024.1.2/bin/pycharm.sh

cowStuff() {

bored=("Moo" "This grass tastes weird" "I love bash" "Can't you tell? I'm a cow!" "Moooo" "Moooooooo" "..." beautiful);
good=("Woohoo!" "It actually worked" "Good job" "Nice work" "Finally" "We did it!" "Not bad!");
bad=("Nooo..." "Where's the typo?" "Here we go again, then" "Stupid computer" "We'll get it next time" "Broke it!");
if [ $RESULT -eq 0 ]; then RANDOM=$$$(date +%s);
	selectedexpression=${good[ $RANDOM % ${#good[@]} ]};
	cowsay $selectedexpression; else RANDOM=$$$(date +%s);
	selectedexpression=${bad[ $RANDOM % ${#bad[@]} ]};
	cowsay -d $selectedexpression; fi
}

export PICO_SDK_PATH=/home/charlie/pico-sdk
export MARTe2_DIR=/home/charlie/MARTe2-dev
export PATH="$PATH:/opt/nvim-linux64/bin"
export PATH="$PATH:/tools/Xilinx/PetaLinux/2024.1/tool/scripts"
export PATH="$PATH:/tools/Xilinx/Vivado/2024.1/bin"
export PATH="$PATH:~/bin"
export PATH="$PATH:~/intelFPGA/18.1/modelsim_ase/linux"
export PYENV_ROOT="$HOME/.pyenv"
export PATH=$PATH:/usr/local/go/bin
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

export STM32_PRG_PATH=/home/charlie/STMicroelectronics/STM32Cube/STM32CubeProgrammer/bin

export NVM_DIR="$HOME/.nvm"

# NVM stuff

load_nvm() {
    unset -f nvm node npm npx
    [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
}

nvm() {
    load_nvm
    nvm "$@"
}

node() {
    load_nvm
    node "$@"
}

npm() {
    load_nvm
    npm "$@"
}

npx() {
    load_nvm
    npx "$@"
}

# Greeting text
uptime -p
cat ~/coolScripts/reminders.txt

. "$HOME/.atuin/bin/env"
eval "$(zoxide init bash)"
eval "$(atuin init bash)"
eval "$(starship init bash)"
